  install_dependencies:
    executor: node_executor
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  lint:
    executor: node_executor
    steps:
      - checkout
      - run: npm run lint

  test_unit:
    executor: node_executor
    steps:
      - checkout
      - run: npm run test:unit

  test_integration:
    executor: node_executor
    steps:
      - checkout
      - run: npm run test:integration

  notify:
    executor: node_executor
    steps:
      - run: |
          echo "Notificando sobre el estado del pipeline"

workflows:
  version: 2
  validate_and_test:
    jobs:
      - lint
  validate_and_test:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test_unit:
          requires:
            - lint
      - test_integration:
          requires:
            - test_

