version: 2.1

executors:
  node_executor:
    docker:
      - image: circleci/node:14

jobs:
  install_dependencies:
    executor: node_executor
    steps:
      - checkout
      - run: npm install

  lint:
    executor: node_executor
    steps:
      - checkout
      - run: npm run lint

  test_unit:
    executor: node_executor
    steps:
      - checkout
      - run: npm run test:unit
    parallelism: 2  # Ejecuta pruebas en 2 contenedores en paralelo

  test_integration:
    executor: node_executor
    steps:
      - checkout
      - run: npm run test:integration

  notify:
    executor: node_executor
    steps:
      - run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "Pipeline completado: '"${CIRCLE_WORKFLOW_ID}"'"}' \
          https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK

workflows:
  version: 2

  # Workflow 1: Validación y Pruebas
  validate_and_test:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test_unit:
          requires:
            - lint
      - test_integration:
          requires:
            - test_unit

  # Workflow 2: Notificación después de las pruebas de integración
  deploy_and_notify:
    jobs:
      - notify:
          requires:
            - test_integration
