version: 2.1

executors:
  node_executor:
    docker:
      - image: circleci/node:16  # Imagen con Node.js 14 preinstalado

jobs:
  install_dependencies:
    executor: node_executor
    steps:
      - checkout  # Clona el código del repositorio
      - run: npm install  # Instala las dependencias del proyecto

  lint:
    executor: node_executor
    steps:
      - checkout
      - run: npm install  # Asegura que las dependencias estén presentes
      - run: npm run lint  # Ejecuta el linter para verificar el estilo de código

  test_unit:
    executor: node_executor
    parallelism: 2  # Corre en paralelo en dos contenedores
    steps:
      - checkout
      - run: npm install  # Asegura que las dependencias estén instaladas
      - run: npm run test:unit  # Ejecuta las pruebas unitarias

  test_integration:
    executor: node_executor
    steps:
      - checkout
      - run: npm install
      - run: npm run test:integration  # Ejecuta las pruebas de integración

  notify:
    executor: node_executor
    steps:
      - run: |
          echo "Notificación: El pipeline se ha completado con éxito"
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "Pipeline completado: '"${CIRCLE_WORKFLOW_ID}"'"}' \
          https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK

workflows:
  version: 2

  complete_pipeline:
    jobs:
      - install_dependencies  # Instala las dependencias
      - lint:
          requires:
            - install_dependencies  # Solo se ejecuta si la instalación fue exitosa
      - test_unit:
          requires:
            - lint  # Ejecuta las pruebas unitarias después del linting
      - test_integration:
          requires:
            - test_unit  # Ejecuta las pruebas de integración después de las unitarias
      - notify:
          requires:
            - test_integration  # Envía notificación tras completar las pruebas
