version: 2.1

executors:
  node_executor:
    docker:
      - image: circleci/node:14

jobs:
  install_dependencies:
    executor: node_executor
    steps:
      - checkout  # Clona el repositorio
      - run: npm install  # Instala las dependencias del proyecto

  lint:
    executor: node_executor
    steps:
      - checkout  # Clona el código
      - run: npm install  # Asegúrate de instalar las dependencias
      - run: npm run lint  # Ejecuta el linter

workflows:
  version: 2
  lint_and_test:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
